version: '3.1'

services:
  drupal:
    image: drupal:10.1.2
    ports:
      - 8080:80
    volumes:
      - ./modules:/var/www/html/modules
      - ./profiles:/var/www/html/profiles
      - ./themes:/var/www/html/themes
     # this takes advantage of the feature in Docker that a new anonymous
     # volume (which is what we're creating here) will be initialized with the
     # existing content of the image at the same location
      - ./sites:/var/www/html/sites
    restart: always
    links:
      - "mysql:mysql"
      # in Drupal installation Setup Database section: Click advanced and change localhost to mysql

  mysql:
    image: mysql
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: 'root' # TODO: Change this
    volumes:
      - ./db:/var/lib/mysql/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8090:80
    environment:  
      PMA_HOST: mysql  